export default {
    state: {
        areaCodeList:
            [{
                code: '+86',
                name: '中国大陆',
                phonePattern: /^1[3|4|5|6|7|8|9][0-9]{9}$/
            }, {
                code: '+93',
                name: '阿富汗',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+355',
                name: '阿尔巴尼亚',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+213',
                name: '阿尔及利亚',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+376',
                name: '安道尔共和国',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+244',
                name: '安哥拉',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+54',
                name: '阿根廷',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+374',
                name: '亚美尼亚',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+61',
                name: '澳大利亚',
                phonePattern: /^4\d{8,9}$/
            }, {
                code: '+43',
                name: '奥地利',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+994',
                name: '阿塞拜疆',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+1242',
                name: '巴哈马',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+973',
                name: '巴林',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+880',
                name: '孟加拉国',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+375',
                name: '白俄罗斯',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+32',
                name: '比利时',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+501',
                name: '伯利兹',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+229',
                name: '贝宁',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+591',
                name: '玻利维亚',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+387',
                name: '波斯尼亚和黑塞哥维那',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+267',
                name: '博茨瓦纳',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+55',
                name: '巴西',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+673',
                name: '文莱',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+359',
                name: '保加利亚',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+226',
                name: '布基纳法索',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+257',
                name: '布隆迪',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+855',
                name: '柬埔寨',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+237',
                name: '喀麦隆',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+1',
                name: '加拿大',
                phonePattern: /^\d{10}$/
            }, {
                code: '+238',
                name: '佛得角',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+1345',
                name: '开曼群岛',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+236',
                name: '中非',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+235',
                name: '乍得',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+56',
                name: '智利',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+57',
                name: '哥伦比亚',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+269',
                name: '科摩罗',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+506',
                name: '哥斯达黎加',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+385',
                name: '克罗地亚',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+599',
                name: '库拉索岛',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+357',
                name: '塞浦路斯',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+420',
                name: '捷克共和国',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+243',
                name: '刚果(金)',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+45',
                name: '丹麦',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+253',
                name: '吉布提',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+1767',
                name: '多米尼克',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+1809',
                name: '多米尼加共和国',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+593',
                name: '厄瓜多尔',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+20',
                name: '埃及',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+503',
                name: '萨尔瓦多',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+240',
                name: '赤道几内亚',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+372',
                name: '爱沙尼亚',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+251',
                name: '埃塞俄比亚',
                phonePattern: /^\d{9,10}$/
            }, {
                code: '+358',
                name: '芬兰',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+33',
                name: '法国',
                phonePattern: /^(\d{6}|\d{8,9})$/
            }, {
                code: '+689',
                name: '法属波利尼西亚',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+241',
                name: '加蓬',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+220',
                name: '冈比亚',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+995',
                name: '格鲁吉亚',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+49',
                name: '德国',
                phonePattern: /^1(\d{5,6}|\d{9,12})$/
            }, {
                code: '+233',
                name: '加纳',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+30',
                name: '希腊',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+1473',
                name: '格林纳达',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+590',
                name: '瓜德罗普',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+502',
                name: '危地马拉',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+224',
                name: '几内亚',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+245',
                name: '几内亚比绍',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+592',
                name: '圭亚那',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+504',
                name: '洪都拉斯',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+852',
                name: '中国香港',
                phonePattern: /^0{0,1}[1,4,5,6,7,8,9](?:\d{7}|\d{8}|\d{12})$/
            }, {
                code: '+36',
                name: '匈牙利',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+354',
                name: '冰岛',
                phonePattern: /^\d{6,8}$/
            }, {
                code: '+91',
                name: '印度',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+62',
                name: '印度尼西亚',
                phonePattern: /^[2-9]\d{7,11}$/
            }, {
                code: '+964',
                name: '伊拉克',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+353',
                name: '爱尔兰',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+44',
                name: '马恩岛',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+972',
                name: '以色列',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+39',
                name: '意大利',
                phonePattern: /^[37]\d{8,11}$/
            }, {
                code: '+225',
                name: '科特迪瓦',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+1876',
                name: '牙买加',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+81',
                name: '日本',
                phonePattern: /^0[7,8,9]0(\d{8})$/
            }, {
                code: '+962',
                name: '约旦',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+7',
                name: '哈萨克斯坦',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+254',
                name: '肯尼亚',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+381',
                name: '科索沃',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+965',
                name: '科威特',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+996',
                name: '吉尔吉斯斯坦',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+856',
                name: '老挝',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+371',
                name: '拉脱维亚',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+961',
                name: '黎巴嫩',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+266',
                name: '莱索托',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+231',
                name: '利比里亚',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+218',
                name: '利比亚',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+423',
                name: '列支敦士登公国',
                phonePattern: /^\d{6,8}$/
            }, {
                code: '+370',
                name: '立陶宛',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+352',
                name: '卢森堡',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+853',
                name: '中国澳门',
                phonePattern: /^6\d{7}$/
            }, {
                code: '+389',
                name: '马其顿',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+261',
                name: '马达加斯加',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+265',
                name: '马拉维',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+60',
                name: '马来西亚',
                phonePattern: /^\d{9,10}$/
            }, {
                code: '+960',
                name: '马尔代夫',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+223',
                name: '马里',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+356',
                name: '马耳他',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+222',
                name: '毛里塔尼亚',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+230',
                name: '毛里求斯',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+52',
                name: '墨西哥',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+373',
                name: '摩尔多瓦',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+976',
                name: '蒙古',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+382',
                name: '黑山共和国',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+212',
                name: '摩洛哥',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+258',
                name: '莫桑比克',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+95',
                name: '缅甸',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+264',
                name: '纳米比亚',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+977',
                name: '尼泊尔',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+31',
                name: '荷兰',
                phonePattern: /^6\d{8}$/
            }, {
                code: '+64',
                name: '新西兰',
                phonePattern: /^(0){0,1}[278]\d{7,9}$/
            }, {
                code: '+505',
                name: '尼加拉瓜',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+227',
                name: '尼日尔',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+234',
                name: '尼日利亚',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+47',
                name: '挪威',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+968',
                name: '阿曼',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+92',
                name: '巴基斯坦',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+970',
                name: '巴勒斯坦',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+507',
                name: '巴拿马',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+675',
                name: '巴布亚新几内亚',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+51',
                name: '秘鲁',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+63',
                name: '菲律宾',
                phonePattern: /^[24579](\d{7,9}|\d{12})$/
            }, {
                code: '+48',
                name: '波兰',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+689',
                name: '波利尼西亚',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+351',
                name: '葡萄牙',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+1787',
                name: '波多黎各',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+974',
                name: '卡塔尔',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+242',
                name: '刚果(布)',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '679',
                name: '斐济共和国',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+40',
                name: '罗马尼亚',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+7',
                name: '俄罗斯',
                phonePattern: /^[13489]\d{9,11}$/
            }, {
                code: '+250',
                name: '卢旺达',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+1869',
                name: '圣基茨和尼维斯',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+1758',
                name: '圣卢西亚',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+590',
                name: '圣马丁',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+1784',
                name: '圣文森特和格林纳丁斯',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+966',
                name: '沙特阿拉伯',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+221',
                name: '塞内加尔',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+381',
                name: '塞尔维亚',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+248',
                name: '塞舌尔',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+232',
                name: '塞拉利昂',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+65',
                name: '新加坡',
                phonePattern: /^[13689]\d{6,7}$/
            }, {
                code: '+421',
                name: '斯洛伐克',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+386',
                name: '斯洛文尼亚',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+252',
                name: '索马里',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+27',
                name: '南非',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+82',
                name: '韩国',
                phonePattern: /^0{0,1}[7,1](?:\d{8}|\d{9})$/
            }, {
                code: '+34',
                name: '西班牙',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+94',
                name: '斯里兰卡',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+597',
                name: '苏里南',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+268',
                name: '斯威士兰',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+46',
                name: '瑞典',
                phonePattern: /^[124-7](\d{8}|\d{10}|\d{12})$/
            }, {
                code: '+41',
                name: '瑞士',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+886',
                name: '中国台湾',
                phonePattern: /^0{0,1}[6,7,9](?:\d{7}|\d{8}|\d{10})$/
            }, {
                code: '+992',
                name: '塔吉克斯坦',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+255',
                name: '坦桑尼亚',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+66',
                name: '泰国',
                phonePattern: /^[13456789]\d{7,8}$/
            }, {
                code: '+685',
                name: '萨摩亚独立国',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+377',
                name: '摩纳哥公国',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+692',
                name: '马绍尔群岛共和国',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+228',
                name: '多哥',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+1868',
                name: '特立尼达和多巴哥',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+216',
                name: '突尼斯',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+90',
                name: '土耳其',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+993',
                name: '土库曼斯坦',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+256',
                name: '乌干达',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '380',
                name: '乌克兰',
                phonePattern: /^[3-79]\d{8,9}$/
            }, {
                code: '+971',
                name: '阿联酋',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+44',
                name: '英国',
                phonePattern: /^[347-9](\d{8,9}|\d{11,12})$/
            }, {
                code: '+1',
                name: '美国',
                phonePattern: /^\d{10,12}$/
            }, {
                code: '+598',
                name: '乌拉圭',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+998',
                name: '乌兹别克斯坦',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+678',
                name: '瓦努阿图共和国',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+58',
                name: '委内瑞拉',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+84',
                name: '越南',
                phonePattern: /^[1-9]\d{6,9}$/
            }, {
                code: '+1284',
                name: '英属维尔京群岛',
                phonePattern: /^\d{6,12}$/
            }, {
                code: '+967',
                name: '也门',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+260',
                name: '赞比亚',
                phonePattern: /^\d{6,15}$/
            }, {
                code: '+263',
                name: '津巴布韦',
                phonePattern: /^\d{6,15}$/
            }]

    },
    mutations: {

    },
    actions: {

    }
}
